const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('/api/scenarios').then(r=>r.json()).then(xs=>xs.forEach(x=>$('#scenario').insertAdjacentHTML('beforeend',`<option value="${esc(x.id)}">${esc(x.label)} — ${esc(x.purpose)}</option>`)));
$('#scenario').onchange=()=>{$('#eml').disabled=!!$('#scenario').value};
$('#form').onsubmit=async e=>{e.preventDefault();$('#error').style.display='none';$('#result').style.display='none';$('#busy').style.display='block';$('#run').disabled=true;try{const r=await fetch('/api/analyze',{method:'POST',body:new FormData(e.target)}),d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed');render(d)}catch(x){$('#error').textContent=x.message;$('#error').style.display='block'}finally{$('#busy').style.display='none';$('#run').disabled=false}};
function renderML(m){const chips=`<div class="compactfacts"><span class="fact">ADVISORY ONLY</span><span class="fact">EXECUTABLE = ${m.executable}</span><span class="fact">RULE SCORE UNCHANGED</span></div>`;
if(!m.available)return`<div class="decisionmark">?</div><div class="big" style="font-size:27px;color:var(--amber)">UNAVAILABLE</div>${chips}<details><summary>Why this signal is unavailable</summary><p class="muted">${esc(m.unavailable_reason||'optional ML runtime or model unavailable')} - reported honestly, never guessed.</p><p class="panelnote">Model ${esc(m.model_version)} · offline inference only</p></details>`;
const pct=(m.phishing_probability*100),toks=m.top_contributing_tokens.length?m.top_contributing_tokens.map(t=>`<span class="tok"><b>${esc(t.token)}</b> +${t.contribution.toFixed(4)}</span>`).join(''):'<span class="muted">no positive token contributions</span>';
return`<div class="signalviz"><div class="probability" style="--pct:${pct}"><b>${pct.toFixed(1)}%</b></div><div><h3>Phishing-language probability</h3><div class="tokenmap">${toks}</div></div></div>${chips}<details><summary>Signal meaning &amp; model limits</summary><p class="muted">One INFO-level advisory evidence item, not a verdict. The deterministic risk score is unchanged. Test-set metrics are not a field claim.</p><p class="panelnote">Model ${esc(m.model_version)} · trained on historical public corpora · offline inference only</p></details>`}
function renderGeo(g){const facts=`<div class="compactfacts"><span class="fact">PROBABLE INFRASTRUCTURE COUNTRY</span><span class="fact">NOT A PERSON'S LOCATION</span><span class="fact">OFFLINE ${esc(g.database.database)}</span></div>`;
if(!g.hop_intelligence.length)return`<div class="geo-path"><div class="hopnode"><b>MAIL</b>NO PUBLIC HOPS</div><div class="hopline"></div><div class="hopnode"><b>LOCAL</b>NO GUESS MADE</div></div>${facts}<details><summary>Geo boundary</summary><p class="muted">No public hop IPs were observed, so there was nothing to resolve. No ASN, WHOIS or reputation is claimed.</p></details>`;
const nodes=g.hop_intelligence.map(h=>{let loc=h.status==='RESOLVED'?(h.country_name||h.country_code):h.status==='INTERNAL_OR_NON_ROUTABLE'?'INTERNAL':h.status==='INVALID_IP'?'INVALID':'UNAVAILABLE';return`<div class="hopnode"><b>HOP ${esc(h.hop_number??'-')}</b>${esc(h.ip)}<br>${esc(loc)}</div>`}).join('<div class="hopline"></div>');
const rows=g.hop_intelligence.map(h=>{let cell;if(h.status==='RESOLVED')cell=`<span class="ok">${esc(h.country_name||h.country_code)} (${esc(h.country_code||'n/a')})</span>`;else if(h.status==='INTERNAL_OR_NON_ROUTABLE')cell='<span class="muted">internal / non-routable - not geolocated</span>';else if(h.status==='INVALID_IP')cell='<span class="muted">invalid IP</span>';else cell=`<span style="color:var(--amber)">unavailable${h.unavailable_reason?` - ${esc(h.unavailable_reason)}`:''}</span>`;return`<tr><td>${esc(h.hop_number??'-')}</td><td><code>${esc(h.ip)}</code></td><td>${cell}</td></tr>`}).join('');
return`<div class="geo-path"><div class="hopnode"><b>MESSAGE</b>RECEIVED CHAIN</div><div class="hopline"></div>${nodes}</div>${facts}<details><summary>Open hop evidence table</summary><p class="muted">${g.summary.resolved} of ${g.summary.hop_ips} hop IP(s) resolved against the bundled offline database.</p><table class="hops"><tr><th>Hop</th><th>IP</th><th>Probable infrastructure country</th></tr>${rows}</table><p class="panelnote">No ASN / WHOIS / reputation in this edition.</p></details>`}
function render(d){$('#score').textContent=`${d.risk.score}`;$('#riskdial').style.setProperty('--risk',d.risk.score);$('#level').innerHTML=`<b>${esc(d.risk.risk_level)}</b> · ${esc(d.risk.confidence)} analytic confidence`;$('#scorebar').style.width=`${d.risk.score}%`;$('#explanation').textContent=d.risk.explanation;$('#subject').textContent=d.email_summary.subject||'(no subject)';$('#meta').textContent=`${d.email_summary.from||'?'} → ${(d.email_summary.to||[]).join?.(', ')||d.email_summary.to||'?'} · ${d.file}`;$('#threat').textContent=`${d.threat.threat_class} · ${d.threat.threat_class_confidence}`;$('#confidence').textContent=`${d.evidence.length} evidence items`;$('#investigation').textContent=d.investigation_id;$('#graph').textContent=d.graph_hash;
$('#ml').innerHTML=renderML(d.ml_phishing_signal);
$('#geo').innerHTML=renderGeo(d.geo_infrastructure);
const counts=d.evidence.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{}),colors={CRITICAL:'#d73741',HIGH:'#eea61e',MEDIUM:'#1746d1',LOW:'#087d5a',INFO:'#687385'};const rail=Object.entries(counts).map(([k,v])=>`<div class="evdot" style="--sev:${colors[k]}">${esc(k)}<b>${v}</b></div>`).join('')||'<div class="evdot">NO FINDINGS<b>0</b></div>';const full=d.evidence.length?d.evidence.map(x=>`<div class="item"><div class="sev">${esc(x.severity)} · ${esc(x.observation_status)} · RELIABILITY ${esc(x.source_reliability)} · CONFIDENCE ${esc(x.analytic_confidence)}</div><b>${esc(x.finding)}</b><div>${esc(x.detail)}</div><code>${esc(x.id)}</code>${x.authentication_provenance?`<div class="origin">Authentication: ${esc(x.authentication_provenance.verification_state)} · independently verified = false</div>`:''}<div class="origin">${x.origins.length} preserved origin(s): ${esc(x.origins.map(o=>o.module+' '+o.source_locator.kind+':'+o.source_locator.path).join(' · '))}</div></div>`).join(''):'<p>No findings.</p>';$('#evidenceList').innerHTML=`<div class="evidence-rail">${rail}</div><details><summary>Inspect all ${d.evidence.length} evidence records &amp; provenance</summary>${full}</details>`;
const p=d.recommendation;$('#recommendation').innerHTML=`<div class="decisionmark">→</div><div class="big">${esc(p.recommended_action)}</div><div class="compactfacts"><span class="fact">${esc(p.action_mode)}</span><span class="fact">HUMAN ${p.requires_human_approval?'REVIEW':'OPTIONAL'}</span><span class="fact danger">EXECUTABLE = ${p.executable}</span></div><details><summary>Reason &amp; operational limits</summary><p>${esc(p.reason)}</p><ul>${p.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${d.contradictions.length?`<p class="danger">${d.contradictions.length} unresolved contradiction(s) require review.</p>`:''}</details>`;
const c=d.case_package;$('#casePackage').innerHTML=`<div class="exportrow"><div><p><b class="${c.verification.valid?'ok':'danger'}">${c.verification.valid?'VALID':'INVALID'}</b> manifest verification · private, non-overwriting, same-filesystem atomic publication</p><p class="muted">${esc(c.case_dir)}</p></div>${c.verification.valid?`<a class="export" href="${esc(c.export_url)}" download>EXPORT VERIFIED CASE <b>ZIP ↓</b><small>JSON · TXT · MANIFEST</small></a>`:''}</div><div class="boundaries">${Object.values(c.artifacts).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><p class="muted">Integrity is re-verified before download. The ZIP is assembled locally from these three generated files only. Manifest detects change; it is not a signature or legal chain-of-custody attestation.</p>`;$('#result').style.display='block';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
