const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('/api/scenarios').then(r=>r.json()).then(xs=>xs.forEach(x=>$('#scenario').insertAdjacentHTML('beforeend',`<option value="${esc(x.id)}">${esc(x.label)} — ${esc(x.purpose)}</option>`)));
$('#scenario').onchange=()=>{$('#eml').disabled=!!$('#scenario').value};
$('#form').onsubmit=async e=>{e.preventDefault();$('#error').style.display='none';$('#result').style.display='none';$('#busy').style.display='block';$('#run').disabled=true;try{const r=await fetch('/api/analyze',{method:'POST',body:new FormData(e.target)}),d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed');render(d)}catch(x){$('#error').textContent=x.message;$('#error').style.display='block'}finally{$('#busy').style.display='none';$('#run').disabled=false}};
function renderML(m){const chips=`<div class="boundaries"><span class="chip">advisory only</span><span class="chip">executable = ${m.executable}</span><span class="chip">never changes the rule score</span><span class="chip">test-set metrics; no field claim</span></div>`;
if(!m.available)return`<div class="big" style="font-size:27px;color:var(--amber)">UNAVAILABLE</div><p class="muted">${esc(m.unavailable_reason||'optional ML runtime or model unavailable')} - reported honestly, never guessed.</p>${chips}<p class="panelnote">Model ${esc(m.model_version)} · offline inference only</p>`;
const pct=(m.phishing_probability*100);
const toks=m.top_contributing_tokens.length?m.top_contributing_tokens.map(t=>`<span class="tok"><b>${esc(t.token)}</b> +${t.contribution.toFixed(4)}</span>`).join(''):'<span class="muted">no positive token contributions</span>';
return`<h3 class="muted">CALIBRATED PHISHING-LANGUAGE PROBABILITY</h3><div class="big">${pct.toFixed(1)}%</div><div class="bar"><i style="width:${pct}%"></i></div><p class="muted">One INFO-level advisory evidence item, not a verdict. The deterministic risk score above is unchanged by this signal.</p><h3>Tokens that drove this probability</h3><div>${toks}</div>${chips}<p class="panelnote">Model ${esc(m.model_version)} · trained on historical public corpora · offline inference only</p>`}
function renderGeo(g){const chips=`<div class="boundaries"><span class="chip">probable infrastructure country</span><span class="chip">not a person's location</span><span class="chip">offline ${esc(g.database.database)}</span><span class="chip">no ASN / WHOIS / reputation in this edition</span></div>`;
if(!g.hop_intelligence.length)return`<p class="muted">No public hop IPs were observed in this email's Received chain, so there was nothing to resolve. Absence is reported, never guessed.</p>${chips}`;
const rows=g.hop_intelligence.map(h=>{let cell;if(h.status==='RESOLVED')cell=`<span class="ok">${esc(h.country_name||h.country_code)} (${esc(h.country_code||'n/a')})</span>`;else if(h.status==='INTERNAL_OR_NON_ROUTABLE')cell='<span class="muted">internal / non-routable - not geolocated</span>';else if(h.status==='INVALID_IP')cell='<span class="muted">invalid IP</span>';else cell=`<span style="color:var(--amber)">unavailable${h.unavailable_reason?` - ${esc(h.unavailable_reason)}`:''}</span>`;return`<tr><td>${esc(h.hop_number??'-')}</td><td><code>${esc(h.ip)}</code></td><td>${cell}</td></tr>`}).join('');
return`<p class="muted">${g.summary.resolved} of ${g.summary.hop_ips} hop IP(s) resolved against the bundled offline database.</p><table class="hops"><tr><th>Hop</th><th>IP</th><th>Probable infrastructure country</th></tr>${rows}</table>${chips}`}
function render(d){$('#score').textContent=`${d.risk.score}/100`;$('#level').innerHTML=`<b>${esc(d.risk.risk_level)}</b> · ${esc(d.risk.confidence)} analytic confidence`;$('#scorebar').style.width=`${d.risk.score}%`;$('#explanation').textContent=d.risk.explanation;$('#subject').textContent=d.email_summary.subject||'(no subject)';$('#meta').textContent=`${d.email_summary.from||'?'} → ${(d.email_summary.to||[]).join?.(', ')||d.email_summary.to||'?'} · ${d.file}`;$('#threat').textContent=`${d.threat.threat_class} · ${d.threat.threat_class_confidence}`;$('#confidence').textContent=`${d.evidence.length} evidence items`;$('#investigation').textContent=d.investigation_id;$('#graph').textContent=d.graph_hash;
$('#ml').innerHTML=renderML(d.ml_phishing_signal);
$('#geo').innerHTML=renderGeo(d.geo_infrastructure);
$('#evidenceList').innerHTML=d.evidence.length?d.evidence.map(x=>`<div class="item"><div class="sev">${esc(x.severity)} · ${esc(x.observation_status)} · RELIABILITY ${esc(x.source_reliability)} · CONFIDENCE ${esc(x.analytic_confidence)}</div><b>${esc(x.finding)}</b><div>${esc(x.detail)}</div><code>${esc(x.id)}</code>${x.authentication_provenance?`<div class="origin">Authentication: ${esc(x.authentication_provenance.verification_state)} · independently verified = false</div>`:''}<div class="origin">${x.origins.length} preserved origin(s): ${esc(x.origins.map(o=>o.module+' '+o.source_locator.kind+':'+o.source_locator.path).join(' · '))}</div></div>`).join(''):'<p>No findings.</p>';
const p=d.recommendation;$('#recommendation').innerHTML=`<div class="big" style="font-size:27px">${esc(p.recommended_action)}</div><p>${esc(p.reason)}</p><div class="boundaries"><span class="chip">mode ${esc(p.action_mode)}</span><span class="chip">human approval ${p.requires_human_approval}</span><span class="chip danger">executable = ${p.executable}</span></div><h3 style="margin-top:18px">Limits</h3><ul>${p.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${d.contradictions.length?`<p class="danger">${d.contradictions.length} unresolved contradiction(s) require review.</p>`:''}`;
const c=d.case_package;$('#casePackage').innerHTML=`<div class="exportrow"><div><p><b class="${c.verification.valid?'ok':'danger'}">${c.verification.valid?'VALID':'INVALID'}</b> manifest verification · private, non-overwriting, same-filesystem atomic publication</p><p class="muted">${esc(c.case_dir)}</p></div>${c.verification.valid?`<a class="export" href="${esc(c.export_url)}" download>EXPORT VERIFIED CASE <b>ZIP ↓</b><small>JSON · TXT · MANIFEST</small></a>`:''}</div><div class="boundaries">${Object.values(c.artifacts).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><p class="muted">Integrity is re-verified before download. The ZIP is assembled locally from these three generated files only. Manifest detects change; it is not a signature or legal chain-of-custody attestation.</p>`;$('#result').style.display='block';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
